language: go
go:
- 1.12
env:
  global:
  - GO111MODULE=on
  - secure: jsI88hoE5j+ffbxf6hvbA7mtkizkHrmd/RmqFncATUAgE7ny8W0P1pN9wXqncMD/9YaG7cic1H/+NuYuH+cU/GHKkAR2AY8Rbf+4uGiATMfG7tuySVYDdwdYEQKcKXJ6rHSU8oNLBVckZJNv1bqk+LEHhzEXUI7sFEwxvcmTb/zH8TXf5TyTpquW9CWwzsudbl6RRYuzU2DIFBh99/4umY/94FHOHnxm/AENMnsiIjRCZtdqpVdvtaY43rQphotmzR+5IwvMaT/7jxwtksR5HAuEZ2eFQd1+mpOeqddZJ3eigx/DvTkH6N22NmAZL3b2oJKzBDAJCjz/f6rBiEpZBlO8fSHKKMR3XZySbJgNEL7TYr6jEKwNsFo5Bkcj2qKtrPwswxTCihPVBb2QhimN7zvCFi1KgZRcUr4d+FP6YGXsFoBRggDpeNt1x2EXjusfHEnuJY/uoypwJSi2vlGqXuNb45nBVUXS5CIz/kTr2KwYT9sPn/V59TiEuqefX3D3PASzQY/NVd4gcPSZCAXUMs0IA50qfo3/sBW/tFABdhcMhzjEOHc0fJeUAFn+w8O2xmigifUdqh6nPh/4TODSWwlFk+icwDDNdInAOCxThGHamuB1Jlr4P7UvG1itUnQT8hnAcRe8/VjD8b9QGIR9mLbCVFYpAc7PfbN3hrRgzgc=
before_script:
- go get github.com/mattn/goveralls
script:
- make test build
- "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN"
