language: go
go:
- 1.12
env:
  global:
  - GO111MODULE=on
  - secure: MG/w9ZlxK+XhfWXQuwOZWrDc1d8n6mnP/Xl0RcbR9z9O2MY7P/ck91QmBC+RVA5ZuXI7kQQKur9n0FwOHqoaUHO6zyQgvXzO4LQGU9YgTR5W99VyYgwJ2qqRykNfKt7Tzr44MYMRo4rgnTVf4vlm6jfZ6GqL+4wF3iwPg/ZYA4fYyPDhgL9mdsFwI23SZdaqcxvH0SJIzz/7aPfcfCkjmmNEOTPBzjveYFUv+Fmt1sHV7m1iNSB4rC4mRj6FLZbkHhm+4X20edgrsuLQRN3BFjrUcYn/IJ1iFaAs7eligVzg2XdwSYKUUNmzzoBb7+lgIm/MHR9PM+SmRzXQ4btOtKLLBSR2jykHG862VVVnBkn1z0lC9gVhMc6yDna8rJfZIZlYvrVKa+3NzrUNTX05kf7mWiT8n784LIjFiMl70b2r56mdqJC8KJ0JHYjvDDbQy0xJv8Oq+wRdYJfSS4lO6A+Lgfq4jJgXEpF03vwysAiukr1z+ejgKImaUOaQtuhRYSx1ebnOMB1k6STDN7HKb/39yksRhxwtPVC2xhYtKH138jNoyYfPLl/MYaqNHguqyTcZ0DdzxHLJ58+JOXu06iDC4NM5B2zKAOioLzPdVdoHm20ypgbNsVxSX8asyQW0YzFalf/r9gieA2JN6IM1bdFfrA6kidzxDZjuW2UsMfs=

before_script:
- go get github.com/mattn/goveralls

script:
- make test build
- $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
