language: go
go:
- 1.12
env:
  global:
  - GO111MODULE=on
  - secure: PeAdbsLoBuD8FEwUNeT3mgFaDJ7ZKnRbTbA4PNS1cz6mcmfuEMqkVU0qkm7euuXrbRDzRg1GqSdw1ID+rB3Tyg4nBIJrZvgOgaHAWtpxahDUxd6yvh4Mc8iJGaR1yoB4i+frs6ofT92qwIDxM26df6Ib2HdVi2LUOHywBONLKFg7QOcaD9My2F19YfPfafX/JqBatNAqNsJmx/8qa8j8lRkG9VESR+3Tp9rdKTqCUBBpXUqFrp+KSWp/W2toICJ70VWCPN2htfkebxsziriv9Kr0524+4vHDAIQFROBkYi/Yne8D+OHtVhFU6FjcnuW/nPIh02u2itx/lh8c719mJsrHDgc97d+ItcO96DdCzl/l0F+okQASpJ8qxlijgkWTaZudP8ncj48jSirYwBaRsR3GQ0EYGD9dhR+HyGCEl11NSZQKXcwKpPo5YV5F5YgAX7DoJdFqFD5ERhEIFD2Rya8e91S2al4qIDlFR4mSx5y68V8oJfFSzs1H58IcACGcc6i0OKHWroMseGOSZWJQDVkCn1xYpzdZnQKUELKe962sSAUYMFvm959zX3uo3y6xgCDDNluLFXbs6MPtfKIJM6EdzLd5AQ2gu0TkbptEorlw2GaMv/ZqMZ3mE4GqS+Ci+PtN4PvFqMa/0lQGXpck7TdpCwbzWKsgmH6ilIBv1Yw=
before_script:
- go get github.com/mattn/goveralls
script:
- make test build
- "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
