baseURL = "https://tamada.github.io/heatman/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "heatman"
theme = "cayman-hugo-theme"
enableEmoji = true
googleAnalytics = "UA-62401730-12"

pygmentsCodefences = true
pygmentsStyle = "pygments"

[params]
    project_name = "heatman"
    project_logo = "images/heatman.svg"
    project_tagline = "Create heat map image from given csv file."
    dateFormat = "2006-01-02"

    footer = "[![GitHub](https://img.shields.io/badge/GitHub-tamada/goheatman-blueviolet.svg?logo=github)](https://github.com/tamada/goheatman) Made with [Hugo](https://gohugo.io/). Theme by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [GitHub Pages](https://pages.github.com/)."

    katex = true

[menu]
    [[menu.nav]]
        name = ":house: Home"
        url = "/"
        weight = 10
    [[menu.nav]]
        name = ":anchor: Install"
        url = "/install"
        weight = 20
    [[menu.nav]]
        name = ":fork_and_knife: Usage"
        url = "/usage"
        weight = 30
    [[menu.nav]]
        name = ":smile: About"
        url = "/about"
        weight = 40
